# version: "3.9"

services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - pg-network
    depends_on:
      - pgdatabase

  taxi_ingest:
    image: taxi_ingest:v001
    container_name: taxi_ingest
    networks:
      - pg-network
    depends_on:
      - pgdatabase
    entrypoint: ["python", "ingest_data.py"]
    command:
      - "--pg-user=root"
      - "--pg-pass=root"
      - "--pg-host=pgdatabase"
      - "--pg-port=5432"
      - "--pg-db=ny_taxi"
      - "--target-table=yellow_taxi_trips"
    stdin_open: true
    tty: true

volumes:
  ny_taxi_postgres_data:
  pgadmin_data:

networks:
  pg-network:
    driver: bridge